image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: npm i -g nodemon && mkdir -p data && mongod --dbpath data 
  - name: Running Heroku
    command: npm install -g heroku
  - name: install dotenv
    command: npm i dotenv
  - name: instal modules
    command: npm i fs path del multer http path express fs xslt-processor xml2js cors morgan body-parser
    
